name: houses
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - codecov
  - conda-build
  - pip:
    - scikit-learn==1.1.2
    - numpy==1.23.1
    - pytest==7.1.2
    - pre-commit==2.20.0
    - pylint==2.14.0
    - pandas==1.4.3
    - click==8.1.3
    - pytest==7.1.2
    - ipykernel==6.15.1
    - plotnine==0.9.0
variables:
  VAR1: valueA
  VAR2: valueB
  GAGAGA: DADADA
